on: push
jobs:
  buid-node:
    runs-on: ubuntu-latest
    container: python:3.15.0a2-trixie
    steps:
      - run: echo "Tarea Dorx"
      - run: python --version
      - uses: actions/checkout@v3
      - run: python Tarea.py